/**
 * FIFA 3-letter code → ISO 3166-1 alpha-2 code
 * Used to convert a team's fifaCode to an emoji flag.
 */
const FIFA_TO_ISO2: Record<string, string> = {
  // Africa (CAF)
  ALG: 'DZ',
  ANG: 'AO',
  BEN: 'BJ',
  BOT: 'BW',
  BFA: 'BF',
  BDI: 'BI',
  CMR: 'CM',
  CPV: 'CV',
  CAF: 'CF',
  CHA: 'TD',
  CIV: 'CI',
  COD: 'CD',
  CGO: 'CG',
  COM: 'KM',
  DJI: 'DJ',
  EGY: 'EG',
  EQG: 'GQ',
  ERI: 'ER',
  ETH: 'ET',
  GAB: 'GA',
  GAM: 'GM',
  GHA: 'GH',
  GUI: 'GN',
  GBS: 'GW',
  KEN: 'KE',
  LES: 'LS',
  LBR: 'LR',
  LBY: 'LY',
  MAD: 'MG',
  MWI: 'MW',
  MLI: 'ML',
  MTN: 'MR',
  MRI: 'MU',
  MAR: 'MA',
  MOZ: 'MZ',
  NAM: 'NA',
  NIG: 'NE',
  NGA: 'NG',
  RWA: 'RW',
  SEN: 'SN',
  SLE: 'SL',
  SOM: 'SO',
  RSA: 'ZA',
  SDN: 'SD',
  SWZ: 'SZ',
  TAN: 'TZ',
  TOG: 'TG',
  TUN: 'TN',
  UGA: 'UG',
  ZAM: 'ZM',
  ZIM: 'ZW',

  // Asia (AFC)
  AUS: 'AU',
  BHR: 'BH',
  BAN: 'BD',
  BHU: 'BT',
  BRU: 'BN',
  CAM: 'KH',
  CHN: 'CN',
  HKG: 'HK',
  IND: 'IN',
  IDN: 'ID',
  IRN: 'IR',
  IRQ: 'IQ',
  JPN: 'JP',
  JOR: 'JO',
  KAZ: 'KZ',
  PRK: 'KP',
  KOR: 'KR',
  KUW: 'KW',
  KGZ: 'KG',
  LAO: 'LA',
  LBN: 'LB',
  MAC: 'MO',
  MAS: 'MY',
  MDV: 'MV',
  MNG: 'MN',
  MYA: 'MM',
  NEP: 'NP',
  OMA: 'OM',
  PAK: 'PK',
  PHI: 'PH',
  QAT: 'QA',
  KSA: 'SA',
  SAU: 'SA',
  SIN: 'SG',
  SRI: 'LK',
  SYR: 'SY',
  TPE: 'TW',
  TJK: 'TJ',
  THA: 'TH',
  TLS: 'TL',
  TKM: 'TM',
  UAE: 'AE',
  UZB: 'UZ',
  VIE: 'VN',
  YEM: 'YE',

  // Europe (UEFA)
  ALB: 'AL',
  AND: 'AD',
  ARM: 'AM',
  AUT: 'AT',
  AZE: 'AZ',
  BLR: 'BY',
  BEL: 'BE',
  BIH: 'BA',
  BUL: 'BG',
  CRO: 'HR',
  CYP: 'CY',
  CZE: 'CZ',
  DEN: 'DK',
  ENG: 'GB',
  EST: 'EE',
  FIN: 'FI',
  FRA: 'FR',
  GEO: 'GE',
  GER: 'DE',
  GIB: 'GI',
  GRE: 'GR',
  HUN: 'HU',
  ISL: 'IS',
  IRL: 'IE',
  ISR: 'IL',
  ITA: 'IT',
  KOS: 'XK',
  LVA: 'LV',
  LIE: 'LI',
  LTU: 'LT',
  LUX: 'LU',
  MLT: 'MT',
  MDA: 'MD',
  MNE: 'ME',
  NED: 'NL',
  MKD: 'MK',
  NIR: 'GB',
  NOR: 'NO',
  POL: 'PL',
  POR: 'PT',
  ROM: 'RO',
  RUS: 'RU',
  SMR: 'SM',
  SCO: 'GB',
  SRB: 'RS',
  SVK: 'SK',
  SVN: 'SI',
  ESP: 'ES',
  SWE: 'SE',
  SUI: 'CH',
  TUR: 'TR',
  UKR: 'UA',
  WAL: 'GB',

  // CONCACAF
  ATG: 'AG',
  BRB: 'BB',
  BLZ: 'BZ',
  CAN: 'CA',
  CRC: 'CR',
  CUB: 'CU',
  DOM: 'DO',
  SLV: 'SV',
  GRN: 'GD',
  GUA: 'GT',
  HAI: 'HT',
  HON: 'HN',
  JAM: 'JM',
  MEX: 'MX',
  NCA: 'NI',
  PAN: 'PA',
  PUR: 'PR',
  SKN: 'KN',
  LCA: 'LC',
  VIN: 'VC',
  TRI: 'TT',
  USA: 'US',

  // CONMEBOL
  ARG: 'AR',
  BOL: 'BO',
  BRA: 'BR',
  CHI: 'CL',
  COL: 'CO',
  ECU: 'EC',
  PAR: 'PY',
  PER: 'PE',
  URU: 'UY',
  VEN: 'VE',

  // OFC
  FIJ: 'FJ',
  NZL: 'NZ',
  PNG: 'PG',
  SAM: 'WS',
  SOL: 'SB',
  TGA: 'TO',
  VAN: 'VU',
};

/**
 * Convert a FIFA 3-letter code to the ISO 3166-1 alpha-2 code.
 * Returns null if the code is not in the mapping.
 */
export function fifaCodeToIso2(fifaCode: string): string | null {
  return FIFA_TO_ISO2[fifaCode.toUpperCase()] ?? null;
}

/**
 * Return a flagcdn.com image URL for a given FIFA 3-letter code.
 * Uses SVG so the rendered size can be controlled via CSS without depending
 * on flagcdn's limited PNG width variants.
 * e.g., 'BRA' → 'https://flagcdn.com/br.svg'
 * Returns null if the code is not in the mapping.
 */
export function fifaCodeToFlagUrl(fifaCode: string): string | null {
  const iso2 = fifaCodeToIso2(fifaCode);
  if (!iso2) return null;
  return `https://flagcdn.com/${iso2.toLowerCase()}.svg`;
}
